#!/bin/bash

# Auto-update script for Summer 2026 Internships
# This script checks for new internship postings and sends email notifications

# Configuration
REPO_DIR="/Users/kyle/Projects/github-kb/Summer2026-Internships"
LOG_FILE="/Users/kyle/Projects/github-kb/internship-updates.log"
DIFF_FILE="/tmp/internship-diff.txt"
EMAIL_TO="kyleapplyjob@gmail.com"  # Your email for internship notifications

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo "========================================" | tee -a "$LOG_FILE"
echo "$(date): Checking for new internships..." | tee -a "$LOG_FILE"

# Navigate to repo
cd "$REPO_DIR" || exit 1

# Get current commit hash
OLD_COMMIT=$(git rev-parse HEAD)

# Fetch latest changes
git fetch origin dev

# Check if there are updates
NEW_COMMIT=$(git rev-parse origin/dev)

if [ "$OLD_COMMIT" = "$NEW_COMMIT" ]; then
    echo -e "${YELLOW}No new updates found.${NC}" | tee -a "$LOG_FILE"
    exit 0
fi

# Get the diff of new positions
git diff HEAD origin/dev README.md > "$DIFF_FILE"

# Count new positions (lines starting with +<td><strong>)
NEW_POSITIONS=$(grep -c "^+<td><strong><a href" "$DIFF_FILE" || echo "0")

echo -e "${GREEN}Found $NEW_POSITIONS new internship postings!${NC}" | tee -a "$LOG_FILE"

# Pull the changes
git pull origin dev

# Extract new company names and roles
NEW_JOBS=$(grep "^+<td><strong><a href" "$DIFF_FILE" | sed 's/.*company">\(.*\)<\/a>.*/\1/' | head -20)

# Create email body
EMAIL_BODY="/tmp/internship-email.txt"
cat > "$EMAIL_BODY" << EOF
Subject: 🚨 $NEW_POSITIONS New Summer 2026 Internships Available!

Hi there!

$NEW_POSITIONS new internship positions were just posted:

$NEW_JOBS

View all positions at:
file://$REPO_DIR/README.md

Or online at:
https://github.com/SimplifyJobs/Summer2026-Internships

---
Auto-generated by internship tracker
$(date)
EOF

# Send email using macOS mail command
if command -v mail &> /dev/null; then
    cat "$EMAIL_BODY" | mail -s "🚨 $NEW_POSITIONS New Summer 2026 Internships!" "$EMAIL_TO"
    echo -e "${GREEN}Email sent to $EMAIL_TO${NC}" | tee -a "$LOG_FILE"
else
    echo -e "${RED}Mail command not found. Install mailutils or configure SMTP.${NC}" | tee -a "$LOG_FILE"
    echo "Email body saved to: $EMAIL_BODY"
fi

# Display summary
echo "========================================" | tee -a "$LOG_FILE"
echo "Summary:" | tee -a "$LOG_FILE"
echo "- New positions: $NEW_POSITIONS" | tee -a "$LOG_FILE"
echo "- Updated at: $(date)" | tee -a "$LOG_FILE"
echo "- Log file: $LOG_FILE" | tee -a "$LOG_FILE"
echo "========================================" | tee -a "$LOG_FILE"

# Clean up
rm -f "$DIFF_FILE"
